language: generic
dist: xenial

services:
  - docker
script:
  - while sleep 9m; do echo "=====[ Build is still running after $SECONDS seconds ]====="; done &
  - docker login -u $EVAN_DOCKER_USER -p $EVAN_DOCKER_PW
  - docker build -t development .
  - kill %1
