dependencies:
  - boost=1.60.0
  - graphviz
  - nb_conda
  - nodejs
  - pip
  - python=3.6
  - pip:
    - astropy==3.2.3
    - blosc==1.8.1       # Strax dependency
    - boto==2.49.0
    - boto3==1.10.8      # Strax dependency
    - boltons==19.3.0
    - bokeh==1.4.0
    - cython==0.29.14
    - dask==2.9.0
    - datashader==0.9.0
    - datashader==0.9.0
    - dill==0.3.1.1      # Strax dependency
    - flake8==3.7.9
    - flamedisx==0.3.1
    - future==0.18.2
    - hypothesis==4.55.1
    - jupyter==1.0.0
    - jupyterlab==1.2.4
    - holoviews==1.12.7
    - iminuit==1.3.8
    - lz4==2.2.1        # Strax dependency
    - matplotlib==3.1.2
    - multihist==0.6.1
    - nbsphinx
    - numba==0.46.0
    - numpy==1.17.4
    - pandas==0.25.3
    - pandoc==1.0.2
    - psutil==5.6.4     # Strax dependency
    - tables            # pytables, necessary for pandas hdf5 i/o
    - pymongo==3.10.0
    - pytest==5.3.2
    - scikit-learn==0.22
    - scipy==1.3.1
    - sphinx
    - strax==0.8.1
    - tensorflow==2.0.0
    - tensorflow_probability==0.8.0
    - tqdm==4.40.2
    - zstd==1.4.3.2     # Strax dependency
