dependencies:
  - boost=1.60.0
  - graphviz
  - nb_conda
  - nodejs
  - pip
  - python=3.6
  - pip:
    - astropy==3.2.3
    - blosc==1.8.1       # Strax dependency
    - boto==2.49.0
    - boto3==1.10.8      # Strax dependency
    - boltons
    - bokeh
    - cython
    - dask
    - datashader
    - dill==0.3.1.1      # Strax dependency
    - future
    - flake8
    - flamedisx
    - hypothesis
    - jupyter
    - jupyterlab
    - holoviews
    - iminuit
    - lz4==2.2.1        # Strax dependency
    - matplotlib
    - multihist
    - nbsphinx
    - numba==0.46.0
    - numpy==1.17.3
    - pandas==0.25.3
    - pandoc
    - psutil==5.6.4     # Strax dependency
    - tables            # pytables, necessary for pandas hdf5 i/o
    - pymongo==3.9.0
    - pytest
    - scikit-learn
    - scipy==1.3.1
    - sphinx
    - strax
    - tensorflow==2.0.0
    - tensorflow_probability
    - tqdm==4.37.0
    - zstd==1.4.3.2     # Strax dependency
