channels:
  - conda-forge
channel_priority: strict
dependencies:
  - cmake=3.18.2
  - graphviz
  - pip
  - python=3.12
  - pip:
    - -r extra_requirements/requirements-tests.txt
    - -r requirements.txt
