dependencies:
  - cmake=3.18.2
  - graphviz
  - conda-forge::nodejs=18.15.0
  - anaconda::openldap
  - pip
  - python=3.12
  - pip:
    - -r extra_requirements/requirements-tests.txt
    - -r requirements.txt
