name: Duplications detection
on:
  workflow_dispatch:
  release:
    types: [ created ]
  pull_request:
  push:
    branches:
      - master
      - stable

jobs:
  duplications-detection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run the command and capture output
      id: detector
      run: |
        bash .github/scripts/detect_duplications.sh > duplicated.txt
        ls -l
      shell: bash

    - name: Check if duplicated is empty
      run: |
        ls -l
        if [ -s "duplicated.txt" ]; then
          echo "No duplications detected between requirements.txt and extra_requirements/requirements-tests.txt"
        else
          echo -e "Duplications detected between requirements.txt and extra_requirements/requirements-tests.txt\nThey are:"
          cat duplicated.txt
          exit 1
        fi
